### ISSUE TITLE
HA support?

### ISSUE THREAD

**Issue by natlibfi-arlehiko** [indexdata/yazproxy#6]
Hi,

Does YAZ proxy support HA (High Availability)? In other words, does it matter to which instance of YAZproxy the client request is forwarded to, is there any session data stored by the application?

**Comment by adamdickmeiss** [comment]
The Z39.50 protocol is stateful and is bound to the socket.. So from that point of view - it's not HA friendly. If HA Proxy keeps the socket open and contact the _same_ yazproxy instance, then it should be fine.

**Comment by natlibfi-arlehiko** [comment]
> The Z39.50 protocol is stateful and is bound to the socket.. So from that point of view - it's not HA friendly. If HA Proxy keeps the socket open and contact the _same_ yazproxy instance, then it should be fine.

Fair enough. But if using only SRU, does it matter to which YAZ proxy instance the request lands?

**Comment by adamdickmeiss** [comment]
SRU should be fine

**Comment by dltj** [comment]
Hi @natlibfi-arlehiko -- did this answer your question?

--
Peter Murray
Open Source Community Advocate
Index Data, LLC

**Comment by natlibfi-arlehiko** [comment]
Well, I suppose it works. But caching probably isn't as efficient as with single instance because all instances will have their own caches?

https://software.indexdata.com/yazproxy/doc/query-cache.html
https://software.indexdata.com/yazproxy/doc/query-cache.html

**Comment by adamdickmeiss** [comment]
Correct. But some backend systems are based on either Metaproxy or yazproxy will that caching already.

**Comment by dltj** [comment]
Thanks for getting in touch with us, @natlibfi-arlehiko.
--
Peter Murray
Open Source Community Advocate
Index Data, LLC
